### ISSUE TITLE
ImportError: /root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE

### ISSUE THREAD

**Issue by JustBreeze** [924973292/MambaPro#4]
Traceback (most recent call last):
  File "/root/autodl-tmp/MambaPro-master/train_net.py", line 3, in <module>
    from modeling import make_model
  File "/root/autodl-tmp/MambaPro-master/modeling/__init__.py", line 1, in <module>
    from .make_model import make_model
  File "/root/autodl-tmp/MambaPro-master/modeling/make_model.py", line 9, in <module>
    from modeling.fusion_part.AAM import AAM
  File "/root/autodl-tmp/MambaPro-master/modeling/fusion_part/AAM.py", line 5, in <module>
    from modeling.fusion_part.mamba import MM_SS2D
  File "/root/autodl-tmp/MambaPro-master/modeling/fusion_part/mamba.py", line 25, in <module>
    from selective_scan.selective_scan import selective_scan_fn
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan/__init__.py", line 8, in <module>
    from .selective_scan_interface import SelectiveScanFn, selective_scan_fn, selective_scan_ref
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan/selective_scan_interface.py", line 8, in <module>
    import selective_scan_cuda_core as selective_scan_cuda
ImportError: /root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE

I have installed the environment as required, but it keeps reporting errors when I run it.

**Comment by 924973292** [comment]
Thanks for your attention. Please check if your CUDA version is correct, as this error seems to be caused by CUDA. Additionally, the main installation process for Mamba comes from Vmamba, you can refer to their detailed documentation for installation.
Similar ques. can be found here. [Answer](https://github.com/state-spaces/mamba/issues/28)

**Comment by JustBreeze** [comment]
Thanks for your reply, I couldn't find the problem. The cuda I have installed is version 11.8 and the required environment is installed as per the requirements you gave.









徐兆德
***@***.***

签名由 网易灵犀办公 定制









Original:
From：Yuhao Wang ***@***.***>Date：2024-12-26 11:00:47(中国 (GMT+08:00))To：924973292/MambaPro ***@***.***>***@***.***> , Author ***@***.***>Subject：Re: [924973292/MambaPro] ImportError: /root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE (Issue #4)
Thanks for your attention. Please check if your CUDA version is correct, as this error seems to be caused by CUDA. Additionally, the main installation process for Mamba comes from Vmamba, you can refer to their detailed documentation for installation.

**Comment by 924973292** [comment]
You may try the reply [here](https://github.com/state-spaces/mamba/issues/28).

pip install causal_conv1d==1.1.1
pip install mamba-ssm==1.2.0.post1

**Comment by JustBreeze** [comment]
Thank you very much, I will try it.








徐兆德
***@***.***

签名由 网易灵犀办公 定制









Original:
From：Yuhao Wang ***@***.***>Date：2024-12-27 13:29:58(中国 (GMT+08:00))To：924973292/MambaPro ***@***.***>***@***.***> , Author ***@***.***>Subject：Re: [924973292/MambaPro] ImportError: /root/miniconda3/envs/mamba2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE (Issue #4)
You may try the reply here.
pip install causal_conv1d==1.1.1
 pip install mamba-ssm==1.2.0.post1

**Comment by liyali337** [comment]
> You may try the reply [here](https://github.com/state-spaces/mamba/issues/28).
> pip install causal_conv1d==1.1.1 pip install mamba-ssm==1.2.0.post1

hello， I'm having the same issue and I'm using
 pip install causal_conv1d==1.1.1，
pip installs mamba-ssm==1.2.0.post1，
 an error is still reported

/home/user/miniconda3/envs/MambaPro2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE
  File "/home/liyali/MambaPro/selective_scan/selective_scan/selective_scan_interface.py", line 7, in <module>
    import selective_scan_cuda_core as selective_scan_cuda
  File "/home/user/MambaPro/selective_scan/selective_scan/__init__.py", line 8, in <module>
    from .selective_scan_interface import SelectiveScanFn, selective_scan_fn, selective_scan_ref
  File "/home/user/MambaPro/modeling/fusion_part/mamba.py", line 25, in <module>
    from selective_scan.selective_scan import selective_scan_fn
  File "/home/user/MambaPro/modeling/fusion_part/AAM.py", line 5, in <module>
    from modeling.fusion_part.mamba import MM_SS2D
  File "/home/user/MambaPro/modeling/make_model.py", line 9, in <module>
    from modeling.fusion_part.AAM import AAM
  File "/home/user/MambaPro/modeling/__init__.py", line 1, in <module>
    from .make_model import make_model
  File "/home/user/MambaPro/train_net.py", line 3, in <module>
    from modeling import make_model
ImportError: /home/user/miniconda3/envs/MambaPro2/lib/python3.10/site-packages/selective_scan_cuda_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE

**Comment by 924973292** [comment]
I will check this today, you may try DeMo first.
Once ok, I will update the ReadMe section and requ.

**Comment by 924973292** [comment]
Please try now, comment here if you have any other questions. @liyali337
